### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by warwickmm** [openelections/openelections-data-tests#10]
@dwillis, I am proposing that we release a new version of the data tests.  After the following pull requests are merged

* #6
* #8
* #9

I will then tag a new version and begin updating the workflow files in the state repositories.  Let me know if there are any other changes that you would like to include before we do so.

See [here](https://github.com/warwickmm/openelections-data-ak/actions/runs/1192517504) for an example build with the new tests.  The Data Tests workflow will consist of 3 jobs, one for each data test.  Failed jobs will create artifacts with logs files containing the full failure messages.

![image](https://user-images.githubusercontent.com/17345532/131878733-a439db1d-039e-41ba-b9bf-a103d501235b.png)

**Comment by dwillis** [comment]
@warwickmm this looks great to me - go for it!

**Comment by warwickmm** [comment]
Tagged [version 1.0.0](https://github.com/openelections/openelections-data-tests/releases/tag/v1.0.0).
